[versions]
kotlin = "2.2.20"
logback = "1.5.21"

[libraries]
htmx = { module = "org.webjars.npm:htmx.org", version = "2.0.8" }
htmx-path-params = { module = "org.webjars.npm:htmx-ext-path-params", version = "2.0.0" }
htmx-ext-sse = { module = "org.webjars.npm:htmx-ext-sse", version = "2.2.4" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
htmx = ["htmx", "htmx-path-params", "htmx-ext-sse"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
