[versions]
cucumber = "7.33.0"
kotest = "6.0.7"
kotlin = "2.3.0"
logback = "1.5.21"

[libraries]
cucumber-java = { group = "io.cucumber", name = "cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform-engine = { group = "io.cucumber", name = "cucumber-junit-platform-engine", version.ref = "cucumber" }
htmx = { module = "org.webjars.npm:htmx.org", version = "2.0.8" }
htmx-ext-sse = { module = "org.webjars.npm:htmx-ext-sse", version = "2.2.4" }
htmx-path-params = { module = "org.webjars.npm:htmx-ext-path-params", version = "2.0.0" }
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-framework-datatest-jvm = { group = "io.kotest", name = "kotest-framework-datatest-jvm", version.ref = "kotest" }
kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotest" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
htmx = ["htmx", "htmx-path-params", "htmx-ext-sse"]
cucumber-libs = [
    "cucumber-java",
    "cucumber-junit-platform-engine"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
